# Generated by Django 6.0.3 on 2026-03-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('avg_sentiment', models.FloatField()),
                ('daily_trend', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('stock_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SilverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_text', models.TextField()),
                ('raw_sentiment_score', models.FloatField(blank=True, null=True)),
                ('raw_sentiment_label', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bronze_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silver_data', to='api.bronzedata')),
            ],
        ),
    ]
